### ISSUE TITLE
Info needed to use the trained model

### ISSUE THREAD

**Issue by ORlGlN** [talonvoice/wav2letter#2]
Hi @lunixbochs, really appreciate your works on wav2letter and Talon!
I have some questions regarding how to run offline inference using the model you provided, specifically this model (https://talonvoice.com/research/e127-specaug-cb5_89-cv12_63-lsc3_00-lso9_28-sc2_16-tal9_41-tat0_45-ted8_42-tts2_12.bin) together with this lm (https://talonvoice.com/research/enwiki-4gram-2019-04.tar.gz).
Would you mind to shed some light on the queries below:
- Is there any info missing such as the decoder options, model architecture?
- How to use this model to do inference offline?
- Which branch of your repo should i use for this particular model?

Thanks in advance.

**Comment by lunixbochs** [comment]
Use the decoder or decoder-ng branch, sorry it's a small pain to build wav2letter and I don't have any advice there right now. The wav2letter streaming stuff is much easier to build, and I have a w2lstream target for that, but that only works with models exported for streaming: https://github.com/facebookresearch/wav2letter/issues/577
