### ISSUE TITLE
Redundant include directives in b2l-decoder branch

### ISSUE THREAD

**Issue by RosenKrumov** [talonvoice/wav2letter#5]
Hello,

When I try to compile the b2l-decoder branch, I see that some files from the w2l dir are including "w2l.h". This file is not existing and its functions are moved to other files, so maybe those includes are redundant?

Thanks in advance!

**Comment by lunixbochs** [comment]
That branch has already been merged into b2l

**Comment by RosenKrumov** [comment]
Thank you!
