### ISSUE TITLE
How to use decoder-ng lib

### ISSUE THREAD

**Issue by RosenKrumov** [talonvoice/wav2letter#6]
Hello! 

I would like to ask if there is currently any binary that is created that properly tests the decoder-ng libs. Also, is there some doc that describes what format of models, token/lexicon files and audio files should be used? 

I saw that wavstream binary is doing some sort of that. Is this binary's purpose to be an example?

Thank you in advance!

Best regards,
Rosen

**Comment by lunixbochs** [comment]
Maybe my web2letter project.
